functions:
  - name: safe_divide
    description: Safely divide
    arguments:                  
      - name: numerator         
        data_type: number
      - name: denominator
        data_type: number
    returns:                    
      data_type: number

  - name: create_email
    description: create email
    arguments:                  
      - name: first_name         
        data_type: varchar
      - name: id
        data_type: number
    returns:                    
      data_type: varchar